# Generated by Django 4.2.4 on 2023-09-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_entry_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Student Entry Year'),
        ),
    ]
