# Generated by Django 4.2.4 on 2023-08-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
        ('accounts', '0002_remove_user_event_user_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='event',
        ),
        migrations.AddField(
            model_name='user',
            name='event',
            field=models.ManyToManyField(blank=True, related_name='participants', to='workshops.event', verbose_name='event'),
        ),
    ]
