# Generated by Django 4.2.4 on 2023-08-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_student_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_voted',
            field=models.BooleanField(default=False, verbose_name='has voted'),
        ),
    ]
