# Generated by Django 4.2.4 on 2023-08-25 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_event_user_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='event',
            new_name='events',
        ),
    ]
