# Generated by Django 4.2.4 on 2023-08-25 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_event_slug'),
        ('accounts', '0005_remove_user_events_user_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='events',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='workshops.event', verbose_name='event'),
        ),
    ]
