# Generated by Django 4.2.4 on 2023-08-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_event_slug'),
        ('accounts', '0006_alter_user_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='events',
        ),
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(blank=True, null=True, related_name='participants', to='workshops.event', verbose_name='Events'),
        ),
    ]
