# Generated by Django 4.2.4 on 2023-08-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_delete_usereventregistration'),
        ('accounts', '0008_remove_user_events_user_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='events',
        ),
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='participants', to='workshops.event', verbose_name='Events'),
        ),
    ]
