# Generated by Django 4.2.4 on 2023-09-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_delete_usereventregistration'),
        ('accounts', '0009_remove_user_events_user_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='events',
        ),
        migrations.AddField(
            model_name='user',
            name='registered_events',
            field=models.ManyToManyField(blank=True, related_name='participants', to='workshops.event', verbose_name='Registered Events'),
        ),
    ]
