# Generated by Django 4.2.4 on 2023-09-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0006_remove_event_registered_users'),
        ('accounts', '0010_remove_user_events_user_registered_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registered_events',
        ),
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='participants', to='workshops.event', verbose_name='Events'),
        ),
    ]
