# Generated by Django 4.2.1 on 2023-08-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_rename_event_image_event_image_remove_event_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
