# Generated by Django 4.2.1 on 2023-08-11 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='election',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='election',
            name='participants',
            field=models.ManyToManyField(related_name='election_as_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vote',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_votes', to='elections.election'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_votes', to='elections.electionoption'),
        ),
    ]
