# Generated by Django 4.2.4 on 2023-08-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_alter_election_election_ended_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='election',
            name='user',
        ),
    ]
