# Generated by Django 4.2.4 on 2023-08-17 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_remove_election_candidate_remove_election_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='election_candidates', to='elections.election', verbose_name='Election Title'),
        ),
    ]
