# Generated by Django 4.2.4 on 2023-09-09 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Last Name')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='mobile number')),
                ('student_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='student number')),
                ('entry_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Entry Year')),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='description')),
                ('capacity', models.IntegerField(verbose_name='capacity')),
                ('election_started_at', models.DateTimeField(verbose_name='Election Start')),
                ('election_ended_at', models.DateTimeField(verbose_name='Election End')),
                ('candidate_registration_start', models.DateTimeField(verbose_name='Candidate Registration Start')),
                ('candidate_registration_end', models.DateTimeField(verbose_name='Candidate Registration End')),
                ('max_votes_per_user', models.PositiveIntegerField(default=1, verbose_name='Maximum Votes Per User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.candidate', verbose_name='candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_votes', to='elections.election')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='election_candidates', to='elections.election', verbose_name='Election Title'),
        ),
    ]
