# Generated by Django 4.2.4 on 2023-09-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_alter_vote_unique_together_vote_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='max_votes_per_user',
            field=models.PositiveIntegerField(default=1, verbose_name='Maximum Votes Per User'),
        ),
    ]
