# Generated by Django 4.2.4 on 2023-09-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_remove_candidate_mobile_candidate_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='email',
        ),
        migrations.AddField(
            model_name='candidate',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='mobile number'),
        ),
    ]
