# Generated by Django 4.2.4 on 2023-08-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_alter_election_candidates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='candidates',
            field=models.ManyToManyField(blank=True, related_name='elections', to='elections.candidate'),
        ),
    ]
