# Generated by Django 4.2.4 on 2023-09-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_election_max_votes_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='description',
            field=models.TextField(null=True, verbose_name='description'),
        ),
    ]
