# Generated by Django 4.2.4 on 2023-09-09 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_candidate_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='candidates',
        ),
    ]
