# Generated by Django 4.2.4 on 2023-09-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(default='-', verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('location', models.TextField(verbose_name='location')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='Capacity')),
                ('price', models.CharField(max_length=50, verbose_name='price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/', verbose_name='Event Image')),
                ('start_event_at', models.DateTimeField(verbose_name='Start Event At')),
                ('end_event_at', models.DateTimeField(verbose_name='End Event At')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
