# Generated by Django 4.2.4 on 2023-08-25 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_usereventregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEventRegistration',
        ),
    ]
