# Generated by Django 4.2.4 on 2023-09-04 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshops', '0004_delete_usereventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registered_users',
            field=models.ManyToManyField(blank=True, related_name='events_attended', to=settings.AUTH_USER_MODEL, verbose_name='Registered Users'),
        ),
    ]
