# Generated by Django 4.2.4 on 2023-09-04 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0005_event_registered_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registered_users',
        ),
    ]
